"""Add unique active session index

Revision ID: 6914abaf5fb4
Revises: 1c98c74b9ab4
Create Date: 2026-08-16 08:34:29.795391
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision: str = '6914abaf5fb4'
down_revision: Union[str, None] = '1c98c74b9ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_one_active_session_per_user', 'game_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_active_session_per_user', table_name='game_sessions', postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###
